#!/usr/bin/env python3
"""
Entry point for the Smart Photo Archive batch processing pipeline.

Usage:
    python -m scripts.run_pipeline --config config.yaml --images-dir /path/to/images
    python -m scripts.run_pipeline --stages clip,tags,captions --resume
    python -m scripts.run_pipeline --stages face_clustering,build_faiss_indices
"""

import argparse
import logging
import sys
import time

# Add project root to path
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from pipeline.orchestrator import PipelineOrchestrator


def setup_logging(verbose: bool = False):
    """Configure logging with timestamps."""
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s │ %(levelname)-8s │ %(name)s │ %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[
            logging.StreamHandler(sys.stdout),
            logging.FileHandler("pipeline.log", mode="a"),
        ],
    )


def parse_args():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Smart Photo Archive — Batch Processing Pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Run all stages on images in ./data/images
  python -m scripts.run_pipeline

  # Run only specific stages
  python -m scripts.run_pipeline --stages clip,tags,captions

  # Resume a previously interrupted run
  python -m scripts.run_pipeline --resume

  # Post-processing only (after all images are embedded)
  python -m scripts.run_pipeline --stages face_clustering,keyword_matching,build_faiss_indices \\
      --keywords-npy data/keyword_embeddings.npy

  # Use a specific GPU
  CUDA_VISIBLE_DEVICES=1 python -m scripts.run_pipeline
        """,
    )
    parser.add_argument(
        "--config",
        default="config.yaml",
        help="Path to config.yaml (default: config.yaml)",
    )
    parser.add_argument(
        "--images-dir",
        default=None,
        help="Override images directory from config",
    )
    parser.add_argument(
        "--stages",
        default=None,
        help="Comma-separated list of stages to run (default: all). "
             "Available: exif,thumbnails,clip,tags,captions,faces,"
             "face_clustering,keyword_matching,build_faiss_indices",
    )
    parser.add_argument(
        "--keywords-npy",
        default=None,
        help="Path to pre-computed keyword embeddings .npy file "
             "(generated by scripts/import_keywords.py)",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume from last checkpoint (default behaviour; flag is a no-op reminder)",
    )
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable debug logging",
    )
    return parser.parse_args()


def main():
    """Main entry point."""
    args = parse_args()
    setup_logging(verbose=args.verbose)

    logger = logging.getLogger("run_pipeline")
    logger.info("=" * 60)
    logger.info("  Smart Photo Archive — Batch Processing Pipeline")
    logger.info("=" * 60)

    stages = None
    if args.stages:
        stages = [s.strip() for s in args.stages.split(",")]
        logger.info("Stages: %s", stages)

    start_time = time.time()

    try:
        orchestrator = PipelineOrchestrator(config_path=args.config)
        orchestrator.run_full_pipeline(
            images_dir=args.images_dir,
            stages=stages,
            keywords_npy_path=args.keywords_npy,
        )
    except KeyboardInterrupt:
        logger.warning("Pipeline interrupted by user.")
    except Exception as e:
        logger.error("Pipeline failed: %s", e, exc_info=True)
        sys.exit(1)

    elapsed = time.time() - start_time
    hours, remainder = divmod(int(elapsed), 3600)
    minutes, seconds = divmod(remainder, 60)
    logger.info("Total time: %dh %dm %ds", hours, minutes, seconds)


if __name__ == "__main__":
    main()
